# Generated by Django 3.1 on 2020-08-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=10, max_digits=2000, null=True)),
                ('status', models.CharField(max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('date_of_payment', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('date_placed', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('order_price', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=10, max_digits=2000, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.payment')),
                ('shipping_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingprovider')),
            ],
        ),
    ]
